#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2015, Fabian Greif
# All Rights Reserved.
#
# The file is part of the lbuild project and is released under the
# 2-clause BSD license. See the file `LICENSE.txt` for the full license
# governing this code.

import os
import sys
import argparse

rootpath = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..")
sys.path.append(rootpath)

import lbuild.parser
import lbuild.logger

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Build libraries from source code repositories')
    parser.add_argument('-r', '--repository',
        dest='repositories',
        action='append',
        help='Folder in which modules are located')
    parser.add_argument('-c', '--configuration',
        dest='config',
        required=True,
        help='Project/library configuration file')
    parser.add_argument('-o', '--outpath',
        dest='outpath',
        default='.',
        help='Path in which the  library will be generated')
    parser.add_argument('-D', '--option',
        dest='options',
        action='append',
        type=str,
        default=[],
        help='Additional options. Options given here will be merged with options '
             'from the configuration file.')
    parser.add_argument('-v', '--verbose',
        action='count',
        default=0,
        dest='verbose')

    args = parser.parse_args()

    lbuild.logger.configure_logger(args.verbose)

    try:
        parser = lbuild.parser.Parser()
        parser.load_repositories(args.config, args.repositories)
        parser.configure_and_build_library(args.config, args.outpath, args.options)
    except lbuild.exception.BlobException as e:
        sys.stderr.write('%s\n' % e)
        sys.exit(1)
