#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2015, Fabian Greif
# All Rights Reserved.
#
# The file is part of the lbuild project and is released under the
# 2-clause BSD license. See the file `LICENSE.txt` for the full license
# governing this code.

import os
import sys
import argparse
import logging
import logging.config

rootpath = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..")
sys.path.append(rootpath)

import lbuild.parser

def configure_logger(verbosity):
    logging.config.dictConfig({
        'version': 1,              
        'disable_existing_loggers': False,
        'formatters': {
            'full': {
                #'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
                'format': '[%(levelname)s] %(name)s: %(message)s'
            },
            'simple': {
                'format': '%(message)s'
            },
        },
        'handlers': {
            'default': {
                'class':'logging.StreamHandler',
                'formatter': 'full',
            },
        },
        'loggers': {
            '': {                  
                'handlers': ['default'],
                'level': 'DEBUG' if verbosity > 1 else ('INFO' if verbosity == 1 else 'WARNING'),
                'propagate': True  
            }
        }
    })

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Build libraries from source code repositories')
    parser.add_argument('-r', '--repository',
        dest='repositories',
        required=True,
        action='append',
        help='Folder in which modules are located')
    parser.add_argument('-c', '--configuration',
        dest='config',
        required=True,
        help='Project/library configuration file')
    parser.add_argument('-o', '--outpath',
        dest='outpath',
        default='.',
        help='Path in which the  library will be generated')
    parser.add_argument('-D', '--option',
        dest='options',
        action='append',
        type=str,
        help='Additional options. Options given here will be merged with options from the configuration file.')
    parser.add_argument('-v', '--verbose',
        action='count',
        default = 0,
        dest='verbose')

    args = parser.parse_args()
    
    configure_logger(args.verbose)
    
    try:
        parser = lbuild.parser.Parser()
        for repofile in args.repositories:
            parser.parse_repository(repofile)
        
        parser.configure_and_build_library(args.config, args.outpath, args.options)
    except lbuild.exception.BlobException as e:
        sys.stderr.write('%s\n' % e)
        sys.exit(1)
